### PR TITLE
auth-email-templates

### LINKED ISSUE #132: Auth Email Templates
- Create email templates for the authentication functionality
- Forgot Password, Reset Password, Register (Admin Invite)

### PR DESCRIPTION
**Pull request by ctc-devops**
- Create email templates for the authentication functionality
- Forgot Password, Reset Password, Register (Admin Invite)
closes #132

### CODE REVIEW

**Comment by meghakak** [comment]
The reset password email was changed in the firebase console since we are using the firebase email template for that. Also, we didn't add the receiver's name in the beginning of the emails - reference #fya-general on slack for reasoning.

**Review by claudeisakeeb — CHANGES_REQUESTED** [review]
Looks great, just had one question about the reset password email:

Are we sure we want "If you did not make this request, feel free to ignore this email." in there as opposed to a prompt to contact an administrator or something?

**Comment by meghakak** [comment]
> 

We just copied whatever was on the figma designs for this, but I believe Justine still needs to confirm these emails with the NPO so we can change the reset password email if they would like to write something else instead.

**Review by claudeisakeeb — APPROVED** [review]
cut the check

**Review by sylvesteryue — APPROVED** [review]
now this...is awesome

**Pull request merged**
