### PR TITLE
change relocate to launched pickup to found a box

### LINKED ISSUE #109: Change Relocate to Launched and Pickup to Found a Box
- change form labels and any labels that refer to relocate/pick up to be relocate/found a box

### PR DESCRIPTION
**Pull request by ctc-devops**
- change form labels and any labels that refer to relocate/pick up to be relocate/found a box
closes #109

### CODE REVIEW

**Review by jeffcheema — COMMENTED** [review]
LGTM!

**Review by jeffcheema — DISMISSED** [review]

**Review by meghakak — CHANGES_REQUESTED** [review]
10/10 B) Could we also change the routes for Found a Box and Launched Box to something like /found-box-form and /launched-box-form?

**Comment by sylvesteryue** [comment]
> 10/10 B) Could we also change the routes for Found a Box and Launched Box to something like /found-box-form and /launched-box-form?

ok should be changed!

**Review by meghakak — APPROVED** [review]
LGTM

**Pull request merged**
