### PR TITLE
gad-pagination

### LINKED ISSUE #146: General + Admin Dashboard Pagination
- Implement pagination for the left and right sidebars of the dashboard
- Reference https://github.com/ctc-uci/find-your-anchor-frontend/pull/91

### PR DESCRIPTION
**Pull request by ctc-devops**
- Implement pagination for the left and right sidebars of the dashboard
- Reference https://github.com/ctc-uci/find-your-anchor-frontend/pull/91
closes #146

### CODE REVIEW

**Review by aliu55 — CHANGES_REQUESTED** [review]
Everything looks good! Can we add pagination to the right sidebar as well?

**Review by meghakak — CHANGES_REQUESTED** [review]
Awesome work!! Thank you for making the common pagination controller. Same comment as Ashley :)

**Review by meghakak — APPROVED** [review]
LGTM

**Review by aliu55 — APPROVED** [review]
LGTM

**Pull request merged**
